### ISSUE TITLE
Efficient Algorithm f or Blinking LED Detection Dedicated to Embedded Systems Equipped with High Perf ormance Cameras

### ISSUE THREAD

**Issue by kakeru-516** [mtrkwsk/pwt_rpc_framework#1]
I have a question about (Efficient Algorithm f or Blinking LED Detection Dedicated to Embedded Systems Equipped with High Perf ormance Cameras). You state that you will have the decoded signal matched, but I am unable to implement your suggested method because I am not sure of the specific matching method. So please tell us specifically about match.

**Comment by mtrkwsk** [comment]
Hello, as I understand you are referting to my paper from EUROCON. Matching means basically getting the unique payload from decoded sequence and comparing it with a list of known sensors' IDs. If you have any questions regarding this topic please write me an email to the address provided in the paper.
